### PR TITLE
Create strassen_matrix_mul.py

### PR DESCRIPTION
**Pull request by Ratnesh4193**
issue #242 
implemented strassen’s matrix multiplication using python

### CODE REVIEW

**Comment by Ratnesh4193** [comment]
@rcoder23 plz review this

**Comment by Ratnesh4193** [comment]
@rcoder23 plz review this

**Comment by Ratnesh4193** [comment]
@Joshitha18 kindly review the PR

**Review by rcoder23 — CHANGES_REQUESTED** [review]
Add driver code with simple input and output

**Comment by Ratnesh4193** [comment]
plz review @rcoder23

**Comment by Ratnesh4193** [comment]
> plz review @rcoder23
 
plz review @rcoder23

**Review by rcoder23 — APPROVED** [review]

**Pull request merged**
