### PR TITLE
Euclidian Algorithm for finding GCD

### PR DESCRIPTION
**Pull request by Tanvie**
## Summary

Implemented Euclidian Algorithm for finding GCD
#161 

Output : 

1. 
image

2.
image

### CODE REVIEW

**Review by rohanbabbar04 — COMMENTED** [review]
Add sample output

**Comment by Tanvie** [comment]
Sample input/output added pl review @rohanbabbar04

**Comment by rohanbabbar04** [comment]
@Tanvie I mean adding the sample I/O in the file as a comment after the code

**Comment by Tanvie** [comment]
Added sample output in the code @rohanbabbar04

**Review by rohanbabbar04 — APPROVED** [review]

**Pull request merged**
