### PR TITLE
Issue 205

### PR DESCRIPTION
**Pull request by srisatya1197**
Hello Sir , I added the code for Fit Squares in triangle problem it's in the codechef beginner level problem. Please review it and let me Know if there is something I need to add.

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
@srisatya1197 Only change the files which are a part of your issue.
Create different branches to solve different issues

**Review by rohanbabbar04 — COMMENTED** [review]
@srisatya1197 Only change the files which are a part of your issue.
Create different branches to solve different issues

**Comment by srisatya1197** [comment]
@rohanbabbar04 Sir can you please tell me how to do that ? What I did is I made three branches to solve three issues.

**Comment by rohanbabbar04** [comment]
You need to make a branch and solve only one issue in that then shift to the second branch and make sure that the changes in the first branch are not there in the second branch then add/commit/push the changes.

**Comment by srisatya1197** [comment]
Sir by tomorrow afternoon I'll make the complete changes please give me the time

**Comment by srisatya1197** [comment]
Sir I'm trying to close the pr's which i made because there are some mistakes I  will do them correctly

**Pull request closed without merging**
