### PR TITLE
Added code for the ATM under issue-128

### PR DESCRIPTION
**Pull request by srisatya1197**
Added the code for issue-128 . I hope this code is right . If not please let me know

### CODE REVIEW

**Comment by srisatya1197** [comment]
@rcoder23 or @Joshitha18 please review it sir/ma'am

**Comment by srisatya1197** [comment]
Please check mine cause I need to add some more codes in folder.

**Comment by rcoder23** [comment]
@srisatya1197 Good work . But Add Complete folder in Topic wise Solution Folder

**Review by rcoder23 — CHANGES_REQUESTED** [review]
Move this solution in Topic wise Folder .

**Comment by srisatya1197** [comment]
Ok Sir will do it

**Comment by srisatya1197** [comment]
So I will try to make the changes Sir if it doesn't show here then I'll make a new pr Sir . This thing is playing with me since two days, So is it ok Sor

**Comment by srisatya1197** [comment]
The other thing is Sir should i create a folder in topic wise questions or create a new folder by naming "codechef"

**Pull request closed without merging**
