### PR TITLE
Sieve_Of_Atkins(#89)

### PR DESCRIPTION
**Pull request by ShubhamGupta577**
Added the code for the Sieve_Of_Atkins
Resolving the issue (#89 )

### CODE REVIEW

**Comment by ShubhamGupta577** [comment]
@Joshitha18 Please review this.

**Comment by ShubhamGupta577** [comment]
@Joshitha18 , Please have a look for this PR.

**Comment by rohanbabbar04** [comment]
When we put an input of 2.
The answer should be No output  whereas the output is [2,3]
When we put an input of 3
The answer should be [2] whereas the output is again [2,3] 
Do correct these two cases otherwise looks good..

**Review by rohanbabbar04 — COMMENTED** [review]
When we put an input of 2.
The answer should be No output whereas the output is [2,3]
When we put an input of 3
The answer should be [2] whereas the output is again [2,3]
Do correct these two cases otherwise looks good..

**Comment by ShubhamGupta577** [comment]
@rohanbabbar04, Requested changes had made. Please review it again.

**Review by rohanbabbar04 — APPROVED** [review]

**Pull request merged**
