### PR TITLE
reverse_of_a_Linked_List #197

### PR DESCRIPTION
**Pull request by ASLManasa**
@rcoder23 sir, I have written the code to reverse a linked list by both iterative as well as recursive  approach #197 Kindly verify it and  merge it. Thank You.

### CODE REVIEW

**Review by rcoder23 — CHANGES_REQUESTED** [review]
Save file in .py extension and try to write code clean .

**Comment by ASLManasa** [comment]
@rcoder23 sir so can i do it under two programs.

**Comment by rohanbabbar04** [comment]
@ASLManasa No files have been changed

**Comment by rcoder23** [comment]
@ASLManasa there is no Updation in file.

**Comment by ASLManasa** [comment]
@rcoder23  yes sir, there was some issue. I am working on it. I will update it soon.

**Pull request closed without merging**
