### PR TITLE
Added n queens

### PR DESCRIPTION
**Pull request by sameeksharl**
implementing N-Queens problem  using backtracking 
Issue no #449

### CODE REVIEW

**Comment by rcoder23** [comment]
@sameeksharl it is Quick sort Program not N-queen

**Comment by rcoder23** [comment]
@sameeksharl  mention issue for this pull request.

**Comment by sameeksharl** [comment]
@rcoder23  could u pls review now?

**Review by rcoder23 — CHANGES_REQUESTED** [review]
Add example input and output

**Comment by rcoder23** [comment]
@sameeksharl Mention issue no.

**Comment by sameeksharl** [comment]
#449

**Comment by sameeksharl** [comment]
#449 issue no

**Review by rcoder23 — CHANGES_REQUESTED** [review]
Add example input and output

**Review by rcoder23 — CHANGES_REQUESTED** [review]
Code is correct .
Add solution in **Master-PyAlgo/Topic Wise Questions with Solutions/Recursion/**  folder

**Comment by sameeksharl** [comment]
Okay will do it !!

**Comment by sameeksharl** [comment]
@rcoder23 done could u check u now?

**Comment by sameeksharl** [comment]
@rcoder23 could u please assign me #459
<https://github.com/Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo/issues/459#issue-895475851>
,
will finish by 12hrs .

**Review by rcoder23 — APPROVED** [review]

**Pull request merged**
