### PR TITLE
add Next Premutation file

### PR DESCRIPTION
**Pull request by soumik2012**
### Have you read the Contributing Guidelines on Pull Requests?

Yes

### Description

Check if the arr is smaller than 2 return the arr same if the array element start larger value then inverse the array, checking the value  larger value swap the position with a smaller element

 
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#397

### CODE REVIEW

**Comment by soumik2012** [comment]
@rcoder23 please check my PR

**Review by rcoder23 — CHANGES_REQUESTED** [review]
For input **3 2 1**
it Give **none**
But correct output should be **1 2 3**

https://leetcode.com/problems/next-permutation/

**Comment by soumik2012** [comment]
@rcoder23 Let me check

**Comment by soumik2012** [comment]
image

my code completely run leet code but not in cmd still confused

**Comment by soumik2012** [comment]
@rcoder23

**Comment by soumik2012** [comment]
> image
> 
> my code completely run leet code but not in cmd i am confused I try every thing @rcoder23

@rcoder23

**Comment by soumik2012** [comment]
@rcoder23 please check my PR i update the code.

**Review by rcoder23 — CHANGES_REQUESTED** [review]
for list **1**
it print none
but answer in 1

**Comment by soumik2012** [comment]
> for list **1**
> it print none
> but answer in 1

@rcoder23  Done please check

**Review by rcoder23 — APPROVED** [review]

**Pull request merged**
