### PR TITLE
Added the code for Chinese Remainder Theorem

### PR DESCRIPTION
**Pull request by srisatya1197**
Hello Sir / ma'am .I have written a code for Chinese Remainder Theorem .Please let me know if there's something I need to change. This is my first contribution to open source . I want to learn more and more .So . Please let me know if there's wrong in my code .Thanks a lot .I want to contribute more in the Master-PyAlgo Project.

### CODE REVIEW

**Comment by Joshitha18** [comment]
@srisatya1197 gives files meaningful names and add comments before functions. Add Time complexity where did u use cont2 function?

**Comment by srisatya1197** [comment]
Ok ma'am . I will change the file names ,add comments before functions ,time complexity. But ma'am I didn't catch you what exactly you are referring there in the last change?

**Comment by srisatya1197** [comment]
Ok ma'am I'll do those .Yes ma'am, I presume that const2 function is not useful over there I will remove it . But ma'am I have a hunch that for changing the names of the files should i make a new pr , to be honest ma'am this is my first contribution after making changes should I again make new branch and all those steps

**Comment by srisatya1197** [comment]
ma'am can you please give me some time to fix those cause I have exams

**Comment by Joshitha18** [comment]
> Ok ma'am I'll do those .Yes ma'am, I presume that const2 function is not useful over there I will remove it . But ma'am I have a hunch that for changing the names of the files should i make a new pr , to be honest ma'am this is my first contribution after making changes should I again make new branch and all those steps

No need to make new pr. Go to branch 'issue-25' from where u made this pr. Make changes add it, commit and Push. Then the changes u made will be visible in this pr

**Comment by Joshitha18** [comment]
> ma'am can you please give me some time to fix those cause I have exams

Try to make requested changes in 2 days

**Comment by srisatya1197** [comment]
Ok ma'am thank you

**Comment by srisatya1197** [comment]
ma'am I made the changes please review it .

**Comment by Joshitha18** [comment]
@srisatya1197 no need to add number of lines/tokens. U just need to add if Time complexity is O(n) or O(n^2). And add example input output

**Comment by srisatya1197** [comment]
Sir by tomorrow afternoon I'll make the complete changes please give me the time

**Pull request closed without merging**
