### PR TITLE
Added Trailing_Zeroes.py

### PR DESCRIPTION
**Pull request by NEERAJAP2001**
Solves #111

### CODE REVIEW

**Comment by NEERAJAP2001** [comment]
@rcoder23 Review Please!

**Review by rcoder23 — CHANGES_REQUESTED** [review]
create new branch then make pull reuest . and add describe what is trailing_zeros number in code using comment

**Comment by NEERAJAP2001** [comment]
My bad I forgot that!! 😬

**Comment by NEERAJAP2001** [comment]
@rcoder23  Kindly refer to #230

**Pull request closed without merging**
