### PR TITLE
implemented breadthFirst Search algorithm

### PR DESCRIPTION
**Pull request by VivanVatsa**
issue #195  task-2 Done
implemented breadth-first search algorithm

### CODE REVIEW

**Comment by rcoder23** [comment]
Create new Pull request.

**Comment by VivanVatsa** [comment]
create the same thing in a new PR @rcoder23 ??

**Comment by rcoder23** [comment]
@VivanVatsa Code for BradthFirst Search algo correct . Just create new Pull request

**Comment by VivanVatsa** [comment]
okay. will do.

**Pull request closed without merging**
