### PR TITLE
Neon number added

### PR DESCRIPTION
**Pull request by ankan1811**
I have added the program to check neon number .Fixes issue #122

### CODE REVIEW

**Comment by ankan1811** [comment]
Please review my PR. @Joshitha18

**Review by rohanbabbar04 — COMMENTED** [review]
Use user defined functions for the problem

**Comment by ankan1811** [comment]
@rohanbabbar04 couldn't understand.Can you elaborate please?

**Comment by rohanbabbar04** [comment]
Don't put everything into the driver code
Define functions put the logic of the code in a function 
In your case put how to check if the number is neon by define neonumber()

**Comment by ankan1811** [comment]
@rohanbabbar04 done.

**Review by rohanbabbar04 — COMMENTED** [review]
Add sample output

**Comment by ankan1811** [comment]
Please review @Joshitha18

**Pull request merged**
