### PR TITLE
Added LinkedLists next set of solutions

### PR DESCRIPTION
**Pull request by NEERAJAP2001**
This PR Has:
Solves #27 
1.Add two Numbers represented by LL
2.Remove Duplicates from unsorted LL
3.Find the first node of the loop in a LL
Thanks.

### CODE REVIEW

**Review by rohanbabbar04 — COMMENTED** [review]
1) Use dynamic input
2) Add a sample I/O after the code

**Comment by NEERAJAP2001** [comment]
@rohanbabbar04 done

**Comment by NEERAJAP2001** [comment]
@Joshitha18 review, please.

**Comment by NEERAJAP2001** [comment]
@rohanbabbar04 any more changes required?

**Pull request closed without merging**
