### PR TITLE
Create Spiral_Traversal_of_Matrix.py

### PR DESCRIPTION
**Pull request by SwarnimaShishodia**

### CODE REVIEW

**Comment by SwarnimaShishodia** [comment]
pls review @rcoder23

**Comment by rcoder23** [comment]
> pls review @rcoder23

Mention for which issue this pull request

**Comment by SwarnimaShishodia** [comment]
> > pls review @rcoder23
> 
> Mention for which issue this pull request

#274

**Review by rcoder23 — APPROVED** [review]
Good work

**Comment by rcoder23** [comment]
Code are correct . But change File position to 
**Topic Wise Questions with Solutions>>Array>>**

**Comment by SwarnimaShishodia** [comment]
> Good work

Thanks!!

**Comment by SwarnimaShishodia** [comment]
> Code are correct . But change File position to
> **Topic Wise Questions with Solutions>>Array>>**

I have done the required changes.

**Pull request merged**
