### PR TITLE
Issue 128

### PR DESCRIPTION
**Pull request by srisatya1197**
I added the ATM code issue #194  . Please let me know if there is something I need to add .

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
@srisatya1197 Do remove the files which are not a part of your issue

**Comment by srisatya1197** [comment]
@rohanbabbar04  Sir may I know how to remove files which are not part of this issue? I have no idea

**Comment by srisatya1197** [comment]
Sir by tomorrow afternoon I'll make the complete changes please give me the time

**Comment by srisatya1197** [comment]
Sir I'm trying to close the pr's which i made because there are some mistakes I will do them correctly

**Pull request closed without merging**
