### PR TITLE
Maximum product subarray 

### PR DESCRIPTION
**Pull request by soumik2012**
### Have you read the Contributing Guidelines on Pull Requests?

Yes 

### Description

I came with a fast and efficient way to solve this problem 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#398

### CODE REVIEW

**Comment by soumik2012** [comment]
@rcoder23 please check my PR

**Comment by soumik2012** [comment]
@rcoder23 please check my PR

**Comment by soumik2012** [comment]
@rcoder23 please check PR

**Comment by soumik2012** [comment]
@rcoder23 please check PR

**Comment by soumik2012** [comment]
@rcoder23 please review my PR

**Review by rcoder23 — APPROVED** [review]

**Pull request merged**
