### PR TITLE
Dijkstra's Algorithm

### PR DESCRIPTION
**Pull request by pranita736**
code for Dijkstra's Algorithm is added.

### CODE REVIEW

**Comment by Joshitha18** [comment]
@pranita736 link the issue of this pr

**Comment by pranita736** [comment]
> @pranita736 link the issue of this pr

I don't have permission to link the issue.

**Comment by Joshitha18** [comment]
@pranita736 mention the issue which was assigned to you to which this pr was made

**Comment by pranita736** [comment]
> @pranita736 mention the issue which was assigned to you to which this pr was made

For issue #49 ,  #20 pr was created.

**Comment by Joshitha18** [comment]
@pranita736 is this made as a part of gssoc?

**Comment by pranita736** [comment]
> @pranita736 is this made as a part of gssoc?

Yes.

**Comment by Joshitha18** [comment]
@pranita736 there was a lot of confusion as u made pr before creating issue and it being assigned. I'll check it but dont create pr without creating issue first. Work on an issue only if it's assigned to u

**Comment by pranita736** [comment]
> @pranita736 there was a lot of confusion as u made pr before creating issue and it being assigned. I'll check it but dont create pr without creating issue first. Work on an issue only if it's assigned to u

Sorry for the confusion.

**Comment by Joshitha18** [comment]
@pranita736 implement a working Dijkstra.py with a graph.

**Pull request closed without merging**
