### PR TITLE
Bubble sort

### PR DESCRIPTION
**Pull request by Swetha126**
I have added the code for bubble sort in python with space, time complexity and sample test case.
I would wish to resolve issue #52
Thank you!

### CODE REVIEW

**Comment by rcoder23** [comment]
@Swetha126 Please make a separate folder as " Sorting Algo" . and add this file in it .

**Comment by ANAMIKA1410** [comment]
hello!! 
I m Anamika , gssoc participant 
i wll write a clean code for it 
please assign this to me

**Review by ANAMIKA1410 — APPROVED** [review]
def bubbleSort(arr): 
    n = len(arr) 
  
    # Traverse through all array elements 
    for i in range(n-1): 
    # range(n) also work but outer loop will repeat one time more than needed. 
  
        # Last i elements are already in place 
        for j in range(0, n-i-1): 
  
            # traverse the array from 0 to n-i-1 
            # Swap if the element found is greater 
            # than the next element 
            if arr[j] > arr[j+1] : 
                arr[j], arr[j+1] = arr[j+1], arr[j]

**Comment by ANAMIKA1410** [comment]
def bubbleSort(arr): 
    n = len(arr) 
  
    # Traverse through all array elements 
    for i in range(n-1): 
    # range(n) also work but outer loop will repeat one time more than needed. 
  
        # Last i elements are already in place 
        for j in range(0, n-i-1): 
  
            # traverse the array from 0 to n-i-1 
            # Swap if the element found is greater 
            # than the next element 
            if arr[j] > arr[j+1] : 
                arr[j], arr[j+1] = arr[j+1], arr[j]

**Comment by Swetha126** [comment]
@rcoder23 i have added my bubble sort code in a new folder called Sorting Algorithms.
Thank you!

**Comment by rcoder23** [comment]
@Swetha126 Good Work !

**Pull request merged**
