### PR TITLE
Added some questions on stacks

### PR DESCRIPTION
**Pull request by Shreejichandra**

### CODE REVIEW

**Comment by Shreejichandra** [comment]
Issue #17 resolved.

**Comment by rcoder23** [comment]
@Shreejichandra Please add One solution in One Pull request .
And Add solution in specific folder. **example :-** remove duplicate letters from string can be added in Strings folder.

**Comment by Shreejichandra** [comment]
Okay, then I guess I should add the solution of valid parenthesis in the strings folder only and should make a new folder "stacks" for the next greater element question. Am I right?

**Comment by rcoder23** [comment]
Yes . You can add "stacks" question in algebra folder

**Pull request closed without merging**
