### PR TITLE
Added Majority element

### PR DESCRIPTION
**Pull request by rohanbabbar04**
Added #385 (Majority Element)
Do review and merge @rcoder23

### CODE REVIEW

**Review by rcoder23 — CHANGES_REQUESTED** [review]
Add solution in topic wise >> array folder

**Comment by rohanbabbar04** [comment]
@rcoder23 Done Do review and merge

**Comment by NEERAJAP2001** [comment]
@rohanbabbar04 the code gives TLE on gfg and leetcode please make sure the code is optimised.

**Comment by rohanbabbar04** [comment]
I have modified the code Do review and merge @rcoder23 
Do check @NEERAJAP2001

**Comment by rohanbabbar04** [comment]
> @rohanbabbar04 the code gives TLE on gfg and leetcode please make sure the code is optimised.

Done

**Review by rcoder23 — APPROVED** [review]

**Pull request merged**
