### PR TITLE
Add Bucket Sort

### PR DESCRIPTION
**Pull request by muthuannamalai12**
I have added the implementation of Bucket Sort
Fixes: #136

### CODE REVIEW

**Comment by rcoder23** [comment]
@muthuannamalai12 add bucket sort in the Algoritms/sorting folder.

**Review by rcoder23 — CHANGES_REQUESTED** [review]
Add solution in the algorithms/Sorting folder

**Comment by muthuannamalai12** [comment]
I have made the required changes @rcoder23

**Comment by rcoder23** [comment]
@muthuannamalai12 update your fork repository and then make pull request .

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12 update your fork repository and then make pull request .

I have updated it now. Can I close this pull request and Open a new one??

**Comment by rcoder23** [comment]
@muthuannamalai12 Yes ! You can

**Comment by muthuannamalai12** [comment]
@rcoder23 I have created a new New PR #165

**Pull request closed without merging**
