### PR TITLE
Index

### PR DESCRIPTION
**Pull request by Ritu01-git**
List index was out of range

### CODE REVIEW

**Comment by Joshitha18** [comment]
@Ritu01-git is this pr made as a part of gssoc?

**Comment by Ritu01-git** [comment]
Yes , I have fixed an issue in reverse array question. Anything I have to change in this pr? @Joshitha18

**Comment by Joshitha18** [comment]
@Ritu01-git u need to make an issue first. It'll be assigned to you and u can make pr. Otherwise it'll not be counted

**Comment by Joshitha18** [comment]
@Ritu01-git did u create issue? Create issue or this wont be counted

**Comment by Ritu01-git** [comment]
Yes I have created , Please check this https://github.com/Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo/issues/171

**Comment by Ritu01-git** [comment]
@Joshitha18 can you please review my pr?

**Pull request merged**
