### PR TITLE
Topic Wise Questions with Solutions/Array/Subarray_with_sum0.py

### PR DESCRIPTION
**Pull request by soumik2012**
### Have you read the Contributing Guidelines on Pull Requests?

Yes I read 

### Description

Adding the file Topic Wise Questions with Solutions/Array/Subarray_with_sum0.py

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#356

### CODE REVIEW

**Comment by soumik2012** [comment]
@ASLManasa please check my PR

**Comment by soumik2012** [comment]
@sayantani11 Please check my PR

**Comment by soumik2012** [comment]
@sayantani11 please check my Issue

**Comment by soumik2012** [comment]
@sayantani11 please check my PR

**Review by sayantani11 — APPROVED** [review]

**Comment by soumik2012** [comment]
@sayantani11 please add gssoc'21 and level 2 label

**Comment by soumik2012** [comment]
@rcoder23 I will request you to add gssoc'21 and level label

**Review by rcoder23 — APPROVED** [review]

**Pull request merged**
